/** IRT item parameters */
export interface ItemParams {
  /** Discrimination parameter (a) */
  a: number;
  /** Difficulty parameter (b) */
  b: number;
  /** Guessing parameter (c) — typically 0.25 for 4-option MC, 0 for free response */
  c: number;
}

/** Student ability estimate with confidence */
export interface AbilityEstimate {
  /** Estimated theta (ability) on the IRT scale */
  theta: number;
  /** Standard error of the estimate */
  standardError: number;
  /** Number of responses used for this estimate */
  responseCount: number;
}

/** A response to a question during adaptive assessment */
export interface AdaptiveResponse {
  questionId: string;
  skillId: string;
  isCorrect: boolean;
  itemParams: ItemParams;
  timeTakenMs: number;
}

/** Session plan generated by the session planner */
export interface SessionPlan {
  studentId: string;
  phases: PhasePlan[];
  reviewSkills: string[];
  focusSkills: string[];
  estimatedDurationMinutes: number;
}

export interface PhasePlan {
  phase: "warmup" | "focus_1" | "brain_break" | "focus_2" | "wrapup";
  targetSkills: string[];
  questionCount: number;
  durationMinutes: number;
  difficultyTarget: number;
}

/** Frontier gap with priority score */
export interface FrontierGap {
  skillId: string;
  skillCode: string;
  skillName: string;
  yearLevel: number;
  masteryProbability: number;
  priorityScore: number;
  downstreamImpact: number;
  yearLevelDistance: number;
  prerequisitesMet: boolean;
}
